class BridgeConfig:
    ROOT_CHAIN_PROVIDER = ""
    ROOT_CHAIN_CONTRACT_ADDRESS = ""
    ROOT_CHAIN_CONTRACT_ABI = ""
    SIDE_CHAIN_PROVIDER = ""
    SIDE_CHAIN_CONTRACT_ADDRESS = ""
    SIDE_CHAIN_CONTRACT_ABI = ""

    # TODO: abi